### ISSUE TITLE
Topic with no subscribers not actually working

### ISSUE THREAD

**Issue by kentcb** [pmcilreavy/AzureEventGridSimulator#1]
Thanks for this project - it's really gonna save me some headaches!

A problem I've run into: topics with no subscribers cause exceptions. If you leave subscribers out altogether you get this:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at AzureEventGridSimulator.Controllers.ApiController.Post() in C:\projects\azureeventgridsimulator\src\AzureEventGridSimulator\Controllers\ApiController.cs:line 35
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
<snip>
```
But even if you define subscribers as an empty array you get the same problem. The only recourse right now seems to be defining a subscriber, even if that subscriber ends up erroring.

**Comment by jumpingfool** [comment]
If you add a null check around line 35 of the api controller so that it reads something like the following you should be able to configure an empty array or even omit subscribers all together in the configuration.

```c#
if (TopicSettings?.Subscribers?.Any() == true)
{
    foreach (var subscription in TopicSettings.Subscribers)
    {
#pragma warning disable 4014
        SendToSubscriber(subscription, events);
#pragma warning restore 4014
    }
}
```

Note: if you use the `Any()` function as above you will also need to add the ` using System.Linq` using statement at the top of the file.

**Comment by pmcilreavy** [comment]
Hi, thanks for reporting this. Apologies for the delay in fixing it. It should now be resolved.
